### PR TITLE
Per-command --help

### PR DESCRIPTION
**Pull request by NorfairKing**
@L7R7 Here you go, please try it out :D

This is necessary before #4 can be merged because otherwise subcommands aren't documented in `--help` at all.

### CODE REVIEW

**Comment by L7R7** [comment]
Looks good at first glance! Nice! Works as expected on commands and subcommands.
Just one thing I found: If a command doesn't have any settings or subcommands, the output isn't optimal:

```
Usage: gitlab-helper show-branches 

Show branches

Available settings:

```

Just like I did with the empty list of commands, the list of settings has to be skipped when there are none.

**Comment by NorfairKing** [comment]
Cool I'll fix that and merge. Ok for you?

**Comment by L7R7** [comment]
Yes!

**Comment by NorfairKing** [comment]
Merged manually.

**Pull request closed without merging**
