### PR TITLE
Improve help text output

### PR DESCRIPTION
**Pull request by NorfairKing**
@L7R7 Did the rebasing myself. Here's the result of your changes applied to the new per-command help texsts.

### CODE REVIEW

**Comment by NorfairKing** [comment]
This is making me think we may be able to get per-command manpages too...

**Comment by L7R7** [comment]
I found one little thing: There are linebreaks in between the options on the first line of the help output:

```
Usage: gitlab-helper (-h|--help) 
 | --version 
 | (--config-file FILE_PATH --group-id GROUP_ID --base-url URL --api-token TOKEN --exclude-projects ID1,ID2,ID3 COMMAND)

...
```
Usage: gitlab-helper update-merge-requests COMMAND -u|--user-id USER_ID (--search-title TXT) 
 | (-s|--search TXT) --[no-]recheck-merge-status --execute|-x

...
```

which, now that I look at them, I find rather weird. I think we should remove those and keep all of them in one line. What do you think?

**Comment by NorfairKing** [comment]
@L7R7 Yes sounds good.
Hold on, I'll give you commit access so you can just push to this branch.

**Comment by NorfairKing** [comment]
@L7R7 You just got commit access. You can build on the `weeder` branch, to minimise merge conflicts.

**Comment by L7R7** [comment]
Done for now :D I just managed to also get rid of some of the extra empty lines as well. Not all of them, but some of them at least

> You can build on the weeder branch, to minimise merge conflicts.

I'm not sure what you mean, let me know if you need me for something to get this over the line

**Comment by NorfairKing** [comment]
Merged manually.

**Pull request closed without merging**
